# -*- coding: utf-8 -*-
# © Copyright EnterpriseDB UK Limited 2013-2021
#
# This file is part of Postgres Backup API.
#
# Postgres Backup API is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Postgres Backup API is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Postgres Backup API.  If not, see <http://www.gnu.org/licenses/>.

# This file was autogenerated by OpenAPI Generator.

import pytest
from pg_backup_api.openapi_server.models.status import Status


class TestSystemInfo:

    @pytest.mark.parametrize(
        "date_str",
        ["2020-01-31T00:00:00.0000+01:00",
         "2020-01-31T00:00:00.0800-04:00"]
    )
    def test_valid_datetime_patterns(self, date_str):
        """Getting an annotation which doesn't exist returns None"""
        sys_info = Status()
        sys_info.last_archived_time = date_str
        sys_info.last_failed_time = date_str
        sys_info.stats_reset = date_str
