
name: Publish

on: 
    push:
        branches:
            - dev/publish-workflow

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Install python
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            - name: Install other deps
              run: |
                sudo apt-get install -y ruby ruby-dev rubygems build-essential python3 virtualenv
            - name: Install fpm
              run: sudo gem install fpm
            - name: Install python deps
              run: pip install virtualenv-tools3
            - name: Build deb
              working-directory: ./packaging
              run: ./pkg deb --debug
            - name: Build rpm
              working-directory: ./packaging
              run: ./pkg rpm --debug
                
